version: "3.7"

services:
  kitty-bot:
    build: ./
    image: kitty-bot
    restart: "unless-stopped"
    env_file:
      - ".env"
    volumes:
      - kitty-db:/data
      - cache:/home/.cache

networks:
  network:

volumes:
  kitty-db:
  cache:
